2024-11-13 09:17:21,345 ERROR: Exception on /static/css/styles.css [GET] [in /Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/app/routes.py", line 105, in before_request
    db.session.commit()
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE users SET last_seen=? WHERE users.id = ?]
[parameters: ('2024-11-13 06:17:21.343181', 1)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-11-13 09:17:21,345 ERROR: Exception on /static/js/theme-toggle.js [GET] [in /Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/app/routes.py", line 105, in before_request
    db.session.commit()
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE users SET last_seen=? WHERE users.id = ?]
[parameters: ('2024-11-13 06:17:21.343838', 1)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-11-13 09:17:26,731 ERROR: Exception on /static/js/script.js [GET] [in /Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/app/routes.py", line 105, in before_request
    db.session.commit()
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/dubinkerus/PycharmProjects/MegaTutorial/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE users SET last_seen=? WHERE users.id = ?]
[parameters: ('2024-11-13 06:17:26.730223', 1)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-11-13 09:18:17,284 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 09:20:04,807 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 09:37:19,384 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 09:37:34,666 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 10:27:24,227 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 10:51:26,305 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 10:56:57,281 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 11:00:03,605 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 11:33:22,089 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 14:13:49,018 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 14:35:10,750 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-13 14:40:02,875 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-14 15:46:01,297 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-14 16:09:40,515 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-14 16:14:30,393 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-14 16:16:28,040 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-20 22:33:07,936 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
2024-11-22 10:50:09,567 INFO: Microblog startup [in /Users/dubinkerus/PycharmProjects/MegaTutorial/app/__init__.py:52]
